[pytest]
#https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-pythonpath
pythonpath = src

#https://docs.pytest.org/en/7.1.x/reference/reference.html#markers
markers =
    easy_operation: mark an easy mathematical operation.
    difficult_operation: mark a difficult mathematical operation.
    webtest: mark a test as a webtest.
    slow: mark test as slow.